version: "3.3"
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ./komga-data/config
        target: /config
      - type: bind
        source: ./komga-data/data
        target: /data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 25600:25600
    user: "1000:1000"
    restart: unless-stopped
