version: "3.8"
services:
  postgres:
    user: root
    container_name: postgres_container 
    image: postgres:14
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - pgnet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    user: root
    image: dpage/pgadmin4
    container_name: pgadmin_container 
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5050:80"
    networks:
      - pgnet
    volumes:
      - pgdata:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  pgdata:
networks:
  pgnet:
